export default {
  0: 'Poisoned Blade',
  1: 'Blinding Winds',
  2: 'Heal',
  3: 'Cleanse',
  4: 'Iron Skin',
  5: 'Speed',
  6: 'Critical Aim',
  7: 'Deathmark',
  16: 'Exhaust',
  17: 'Daze',
  18: 'Explosion',
  19: 'Hardened Shield',
  24: 'Stun',
  25: 'Second Wind',
  28: 'Resurrection',
};
