export default {
  0: 'warrior',
  1: 'knight',
  2: 'thief',
  3: 'archer',
  4: 'priest',
  5: 'wizard',
  6: 'monk',
  7: 'pirate',
  8: 'berserker',
  9: 'seer',
  10: 'legionnaire',
  11: 'scholar',
  16: 'paladin',
  17: 'darkKnight',
  18: 'summoner',
  19: 'ninja',
  20: 'shapeshifter',
  21: 'bard',
  24: 'dragoon',
  25: 'sage',
  26: 'spellbow',
  28: 'dreadKnight',
};
